/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Investment {
    inflationRate?: number;
    compoundingFrequency?: bigint;
    cashflows: Array<Cashflow>;
    interestRate: number;
    initialInvestment: number;
    years: bigint;
    taxRate?: number;
}
export interface FutureValueResult {
    afterTaxFutureValue: number;
    principalWithoutInterest: number;
    preTaxFutureValue: number;
    realFutureValue: number;
    nominalFutureValue: number;
}
export interface Cashflow {
    year: bigint;
    amount: number;
}
export interface backendInterface {
    futureValue(investment: Investment): Promise<FutureValueResult>;
    getValidTextEntries(entries: Array<string>, arg1: string, pattern: string): Promise<Array<string>>;
    isPositiveNumber(number: bigint): Promise<boolean>;
    isTextValid(input: string): Promise<boolean>;
    isValidEmail(email: string): Promise<boolean>;
}
import type { Cashflow as _Cashflow, Investment as _Investment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async futureValue(arg0: Investment): Promise<FutureValueResult> {
        if (this.processError) {
            try {
                const result = await this.actor.futureValue(to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.futureValue(to_candid_Investment_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getValidTextEntries(arg0: Array<string>, arg1: string, arg2: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidTextEntries(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidTextEntries(arg0, arg1, arg2);
            return result;
        }
    }
    async isPositiveNumber(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPositiveNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPositiveNumber(arg0);
            return result;
        }
    }
    async isTextValid(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTextValid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTextValid(arg0);
            return result;
        }
    }
    async isValidEmail(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidEmail(arg0);
            return result;
        }
    }
}
function to_candid_Investment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Investment): _Investment {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inflationRate?: number;
    compoundingFrequency?: bigint;
    cashflows: Array<Cashflow>;
    interestRate: number;
    initialInvestment: number;
    years: bigint;
    taxRate?: number;
}): {
    inflationRate: [] | [number];
    compoundingFrequency: [] | [bigint];
    cashflows: Array<_Cashflow>;
    interestRate: number;
    initialInvestment: number;
    years: bigint;
    taxRate: [] | [number];
} {
    return {
        inflationRate: value.inflationRate ? candid_some(value.inflationRate) : candid_none(),
        compoundingFrequency: value.compoundingFrequency ? candid_some(value.compoundingFrequency) : candid_none(),
        cashflows: value.cashflows,
        interestRate: value.interestRate,
        initialInvestment: value.initialInvestment,
        years: value.years,
        taxRate: value.taxRate ? candid_some(value.taxRate) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
